# -*- coding: utf-8 -*-
"""Recatngle.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GouM-oj3ltFtqeMRJOJpbCmEbIP0rH83
"""

class Rectangle():
  def __init__(self,length,breadth):
    self.length=length
    self.breadth=breadth
    self.A=0
    self.P=0
  def area(self):
    self.A=self.length*self.breadth
  
  def perimeter(self):
    self.P=2*(self.length+self.breadth)

  def display(self):
    print("Length of the rectangle = ",self.length) 
    print("Breadth of the traiangle = ",self.breadth)
    print("Area = ",self.A)
    print("Perimeter = ",self.P)